import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { buildEnrichedPrDescription, type PrDescriptionInput } from '../pr-description-builder';
import type { JiraWebhookEvent } from '@rtb-ai-hub/shared';
import type { FigmaContext } from '../figma-context';
import type { CiRunResult } from '../target-ci';

function makeEvent(overrides?: Partial<JiraWebhookEvent>): JiraWebhookEvent {
  return {
    source: 'jira',
    type: 'issue_updated',
    issueKey: 'PROJ-123',
    issueType: 'Story',
    status: 'In Progress',
    summary: 'Implement login page',
    description: 'Users should be able to log in with email and password.',
    timestamp: '2025-01-01T00:00:00Z',
    payload: {},
    ...overrides,
  };
}

function makeFigmaContext(overrides?: Partial<FigmaContext>): FigmaContext {
  return {
    fileKey: 'abc123',
    fileUrl: 'https://www.figma.com/file/abc123/Design',
    nodeIds: ['1:2'],
    components: [{ name: 'Button', type: 'COMPONENT', description: 'Primary button' }],
    styles: [{ name: 'Primary', styleType: 'FILL', description: 'Primary color' }],
    nodeTreeSummary: 'FRAME: "Login"',
    designTokens: { colors: ['Primary'], fontFamilies: ['Inter'], spacingPattern: '8px grid' },
    ...overrides,
  };
}

function makeCiResults(overrides?: Partial<CiRunResult>): CiRunResult {
  return {
    success: true,
    steps: [
      {
        name: 'lint',
        command: 'pnpm lint',
        success: true,
        exitCode: 0,
        stdout: '',
        stderr: '',
        durationMs: 1200,
      },
      {
        name: 'test',
        command: 'pnpm test',
        success: true,
        exitCode: 0,
        stdout: '',
        stderr: '',
        durationMs: 3400,
      },
      {
        name: 'build',
        command: 'pnpm build',
        success: true,
        exitCode: 0,
        stdout: '',
        stderr: '',
        durationMs: 5600,
      },
    ],
    totalDurationMs: 10200,
    failedStep: null,
    ...overrides,
  };
}

function makeInput(overrides?: Partial<PrDescriptionInput>): PrDescriptionInput {
  return {
    event: makeEvent(),
    env: 'int',
    implementation: {
      plan: 'Create login form component with validation and API integration.',
      files: [
        { path: 'src/components/LoginForm.tsx', content: '...', action: 'add' },
        { path: 'src/api/auth.ts', content: '...', action: 'modify' },
      ],
      tests: [{ path: 'src/components/__tests__/LoginForm.test.tsx', content: '...' }],
      prSuggestion: {
        title: '[PROJ-123] Implement login page',
        description: 'AI-generated implementation for PROJ-123',
      },
    },
    localResults: {
      branchName: 'feature/PROJ-123-implement-login-page',
      baseBranch: 'develop',
    },
    ciResults: null,
    figmaContext: null,
    domainKnowledge: undefined,
    previewUrl: undefined,
    ...overrides,
  };
}

describe('buildEnrichedPrDescription', () => {
  const originalEnv = process.env;

  beforeEach(() => {
    process.env = { ...originalEnv, JIRA_HOST: 'myorg.atlassian.net' };
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  it('generates all sections when full context is provided', () => {
    const result = buildEnrichedPrDescription(
      makeInput({
        figmaContext: makeFigmaContext(),
        domainKnowledge: 'Users table: usr_mst with columns id, email, password_hash.',
        ciResults: makeCiResults(),
        previewUrl: 'https://preview.example.com/PROJ-123',
      })
    );

    expect(result).toContain('## PROJ-123: Implement login page');
    expect(result).toContain('### Context');
    expect(result).toContain('### Requirements');
    expect(result).toContain('### Implementation Plan');
    expect(result).toContain('### Files Changed');
    expect(result).toContain('### Impact Analysis');
    expect(result).toContain('### Domain Knowledge');
    expect(result).toContain('### CI Status');
    expect(result).toContain('Auto-generated by RTB AI Hub (Multi-Agent Pipeline)');
  });

  it('generates only basic sections with minimal context', () => {
    const result = buildEnrichedPrDescription(
      makeInput({
        event: makeEvent({ description: undefined }),
        implementation: {
          plan: '',
          files: [{ path: 'src/index.ts', content: '...', action: 'add' }],
          tests: [],
          prSuggestion: { title: 'Title', description: 'Desc' },
        },
      })
    );

    expect(result).toContain('## PROJ-123');
    expect(result).toContain('### Context');
    expect(result).toContain('### Files Changed');
    expect(result).toContain('### Impact Analysis');
    expect(result).not.toContain('### Requirements');
    expect(result).not.toContain('### Implementation Plan');
    expect(result).not.toContain('### Domain Knowledge');
    expect(result).not.toContain('### CI Status');
  });

  it('omits Figma row when figmaContext is null', () => {
    const result = buildEnrichedPrDescription(makeInput({ figmaContext: null }));

    expect(result).not.toContain('Figma');
    expect(result).not.toContain('figma.com');
  });

  it('includes Figma row when figmaContext is provided', () => {
    const result = buildEnrichedPrDescription(makeInput({ figmaContext: makeFigmaContext() }));

    expect(result).toContain('| Figma |');
    expect(result).toContain('https://www.figma.com/file/abc123/Design');
  });

  it('omits Domain Knowledge section when domainKnowledge is undefined', () => {
    const result = buildEnrichedPrDescription(makeInput({ domainKnowledge: undefined }));

    expect(result).not.toContain('### Domain Knowledge');
  });

  it('omits CI section when ciResults is null', () => {
    const result = buildEnrichedPrDescription(makeInput({ ciResults: null }));

    expect(result).not.toContain('### CI Status');
  });

  it('shows CI failure with output in code block', () => {
    const failedCi = makeCiResults({
      success: false,
      steps: [
        {
          name: 'lint',
          command: 'pnpm lint',
          success: true,
          exitCode: 0,
          stdout: '',
          stderr: '',
          durationMs: 1200,
        },
        {
          name: 'test',
          command: 'pnpm test',
          success: false,
          exitCode: 1,
          stdout: 'FAIL src/auth.test.ts',
          stderr: 'Error: expected true to be false',
          durationMs: 3400,
        },
      ],
      failedStep: {
        name: 'test',
        command: 'pnpm test',
        success: false,
        exitCode: 1,
        stdout: 'FAIL src/auth.test.ts',
        stderr: 'Error: expected true to be false',
        durationMs: 3400,
      },
    });

    const result = buildEnrichedPrDescription(makeInput({ ciResults: failedCi }));

    expect(result).toContain('### CI Status: ❌ Failed');
    expect(result).toContain('- ✅ lint (1200ms)');
    expect(result).toContain('- ❌ test (3400ms)');
    expect(result).toContain('```');
    expect(result).toContain('Error: expected true to be false');
  });

  it('shows CI success with step durations', () => {
    const result = buildEnrichedPrDescription(makeInput({ ciResults: makeCiResults() }));

    expect(result).toContain('### CI Status: ✅ Passed');
    expect(result).toContain('- ✅ lint (1200ms)');
    expect(result).toContain('- ✅ test (3400ms)');
    expect(result).toContain('- ✅ build (5600ms)');
  });

  it('truncates long description to 500 chars', () => {
    const longDesc = 'A'.repeat(600);
    const result = buildEnrichedPrDescription(
      makeInput({ event: makeEvent({ description: longDesc }) })
    );

    expect(result).toContain('A'.repeat(500) + '...');
    expect(result).not.toContain('A'.repeat(501));
  });

  it('truncates long plan to 800 chars', () => {
    const longPlan = 'B'.repeat(900);
    const result = buildEnrichedPrDescription(
      makeInput({
        implementation: {
          plan: longPlan,
          files: [{ path: 'src/x.ts', content: '...', action: 'add' }],
          tests: [],
          prSuggestion: { title: 'T', description: 'D' },
        },
      })
    );

    expect(result).toContain('B'.repeat(800) + '...');
    expect(result).not.toContain('B'.repeat(801));
  });

  it('truncates long domain knowledge to 500 chars', () => {
    const longDomain = 'C'.repeat(600);
    const result = buildEnrichedPrDescription(makeInput({ domainKnowledge: longDomain }));

    expect(result).toContain('C'.repeat(500) + '...');
    expect(result).not.toContain('C'.repeat(501));
  });

  it('lists files and tests with correct counts and action types', () => {
    const result = buildEnrichedPrDescription(makeInput());

    expect(result).toContain('### Files Changed (3)');
    expect(result).toContain('`src/components/LoginForm.tsx` — add');
    expect(result).toContain('`src/api/auth.ts` — modify');
    expect(result).toContain('`src/components/__tests__/LoginForm.test.tsx` — test');
  });

  it('computes correct impact analysis counts and directories', () => {
    const result = buildEnrichedPrDescription(makeInput());

    expect(result).toContain('### Impact Analysis');
    expect(result).toContain('**New files**: 1');
    expect(result).toContain('**Modified files**: 1');
    expect(result).toContain('**Test files**: 1');
    expect(result).toContain('`src/components`');
    expect(result).toContain('`src/api`');
    expect(result).toContain('`src/components/__tests__`');
  });

  it('generates Jira link using JIRA_HOST env var', () => {
    const result = buildEnrichedPrDescription(makeInput());

    expect(result).toContain('[PROJ-123](https://myorg.atlassian.net/browse/PROJ-123)');
  });

  it('falls back to plain issue key when JIRA_HOST is not set', () => {
    delete process.env.JIRA_HOST;
    const result = buildEnrichedPrDescription(makeInput());

    expect(result).toContain('| Jira | PROJ-123 |');
    expect(result).not.toContain('atlassian.net');
  });

  it('generates Figma link from fileUrl', () => {
    const result = buildEnrichedPrDescription(makeInput({ figmaContext: makeFigmaContext() }));

    expect(result).toContain('[Design File](https://www.figma.com/file/abc123/Design)');
  });

  it('handles special characters in description without breaking tables', () => {
    const result = buildEnrichedPrDescription(
      makeInput({
        event: makeEvent({
          description: 'Use `code` and | pipe and # heading in description',
        }),
      })
    );

    expect(result).toContain('### Requirements');
    expect(result).toContain('Use `code` and | pipe and # heading in description');
    expect(result).toContain('| Jira |');
    expect(result).toContain('|------|');
  });

  it('includes preview link when previewUrl is provided', () => {
    const result = buildEnrichedPrDescription(
      makeInput({ previewUrl: 'https://preview.example.com/PROJ-123' })
    );

    expect(result).toContain('| Preview |');
    expect(result).toContain('[Open Preview](https://preview.example.com/PROJ-123)');
  });

  it('omits preview row when previewUrl is undefined', () => {
    const result = buildEnrichedPrDescription(makeInput({ previewUrl: undefined }));

    expect(result).not.toContain('Preview');
  });

  it('blockquotes domain knowledge', () => {
    const result = buildEnrichedPrDescription(makeInput({ domainKnowledge: 'Line 1\nLine 2' }));

    expect(result).toContain('> Line 1');
    expect(result).toContain('> Line 2');
  });

  it('includes footer', () => {
    const result = buildEnrichedPrDescription(makeInput());

    expect(result).toContain('---\n*Auto-generated by RTB AI Hub (Multi-Agent Pipeline)*');
  });

  it('truncates CI failure output to 1000 chars', () => {
    const longStderr = 'E'.repeat(1200);
    const failedCi = makeCiResults({
      success: false,
      failedStep: {
        name: 'build',
        command: 'pnpm build',
        success: false,
        exitCode: 1,
        stdout: '',
        stderr: longStderr,
        durationMs: 5000,
      },
    });

    const result = buildEnrichedPrDescription(makeInput({ ciResults: failedCi }));

    expect(result).toContain('E'.repeat(1000) + '...');
    expect(result).not.toContain('E'.repeat(1001));
  });
});
